"""
scripts/introspect_backtesting.py — dump the REAL API surface of the installed
kernc/backtesting.py (0.6.2) so strategies/engine code is written against
verified signatures, never invented ones.

Run: .venv\\Scripts\\python.exe scripts\\introspect_backtesting.py
Output: backtest/BACKTESTING_API_NOTES.md
"""
from __future__ import annotations

import inspect
import io
import sys
from contextlib import redirect_stdout
from pathlib import Path

import backtesting
from backtesting import Backtest, Strategy
from backtesting.lib import crossover, SignalStrategy, TrailingStrategy, resample_apply, plot_heatmaps

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "backtest" / "BACKTESTING_API_NOTES.md"


def sig_of(obj) -> str:
    try:
        return str(inspect.signature(obj))
    except (TypeError, ValueError):
        return "(no signature)"


def doc_first(obj, n: int = 3) -> str:
    d = (obj.__doc__ or "").strip()
    if not d:
        return "(no docstring)"
    lines = d.splitlines()
    return " | ".join(l.strip() for l in lines[:n] if l.strip())


def main() -> int:
    lines: list[str] = []
    A = lines.append
    A("# backtesting.py 0.6.2 — VERIFIED API NOTES (introspection)")
    A("")
    A("Generated by scripts/introspect_backtesting.py at import-time introspection of the installed package.")
    A(f"Package: {backtesting.__file__}")
    A("")
    A("## Backtest")
    A("")
    A("Signature: `" + sig_of(Backtest) + "`")
    A("")
    A("Doc: " + doc_first(Backtest, 6))
    A("")
    for mname in ["run", "optimize", "plot", "stats"]:
        m = getattr(Backtest, mname, None)
        if m is None:
            A(f"- {mname}: MISSING")
            continue
        A(f"### Backtest.{mname}")
        A("")
        A("Signature: `" + sig_of(m) + "`")
        A("")
        A("Doc: " + doc_first(m, 6))
        A("")
    A("## Strategy")
    A("")
    A("Signature: `" + sig_of(Strategy) + "`")
    A("")
    A("Doc: " + doc_first(Strategy, 4))
    A("")
    A("Attributes / methods:")
    for mname in ["init", "next", "I", "buy", "sell", "position", "equity", "data", "orders"]:
        m = getattr(Strategy, mname, None)
        if m is None:
            A(f"- `{mname}`: MISSING")
            continue
        if callable(m):
            A(f"- `{mname}` signature: `{sig_of(m)}`")
        else:
            A(f"- `{mname}`: attribute ({type(m).__name__})")
    A("")
    A("### Strategy.buy / sell / close")
    A("")
    for mname in ["buy", "sell", "close"]:
        m = getattr(Strategy, mname, None)
        A(f"- `{mname}` signature: `{sig_of(m)}`")
        if m is not None:
            A(f"  doc: {doc_first(m, 2)}")
    A("")
    A("### Position")
    A("")
    from backtesting.backtesting import Position
    A("Position class: `" + str(Position) + "`")
    for mname in ["size", "pl", "pnl", "is_long", "is_short", "close", "sl", "tp"]:
        m = getattr(Position, mname, None)
        if m is None:
            A(f"- Position.{mname}: MISSING")
        elif callable(m):
            A(f"- Position.{mname} signature: `{sig_of(m)}`")
        else:
            A(f"- Position.{mname}: property/attr ({type(m).__name__})")
    A("")
    A("### Order kwargs (buy/sell)")
    A("")
    # Pull the actual buy/sell docstring which lists kwargs
    buy_doc = (Strategy.buy.__doc__ or "").strip()
    A("buy() doc (kwargs list):")
    A("```")
    A(buy_doc[:4000])
    A("```")
    A("")
    A("### lib helpers")
    A("")
    for name, obj in [("crossover", crossover), ("SignalStrategy", SignalStrategy),
                      ("TrailingStrategy", TrailingStrategy),
                      ("resample_apply", resample_apply),
                      ("plot_heatmaps", plot_heatmaps)]:
        A(f"- {name}: {sig_of(obj)}")
        A(f"  doc: {doc_first(obj, 2)}")
    A("")
    A("### Stats keys (from run() on tiny sample)")
    A("")
    # Determine stats keys by running a trivial backtest with the installed version
    try:
        import numpy as np
        import pandas as pd
        n = 60
        idx = pd.date_range("2024-01-01", periods=n, freq="D", tz="UTC")
        rng = np.random.default_rng(7)
        close = 100 + np.cumsum(rng.normal(0, 1, n))
        df = pd.DataFrame({
            "Open": close * 0.999, "High": close * 1.01, "Low": close * 0.99,
            "Close": close, "Volume": rng.integers(1000, 5000, n),
        }, index=idx)

        class _Probe(Strategy):
            def init(self):
                self.sma = self.I(lambda c: pd.Series(c).rolling(5).mean(), self.data.Close)

            def next(self):
                if not self.position and self.data.Close[-1] > self.sma[-1]:
                    self.buy(sl=self.data.Close[-1] * 0.95, tp=self.data.Close[-1] * 1.05)
                elif self.position and self.data.Close[-1] < self.sma[-1]:
                    self.position.close()

        bt = Backtest(df, _Probe, cash=10_000, commission=0.0001)
        stats = bt.run()
        A("stats index (pandas Series):")
        A("```")
        A(str(list(stats.index)))
        A("```")
        A("")
        A("sample stats values:")
        A("```")
        buf = io.StringIO()
        with redirect_stdout(buf):
            print(stats.to_string())
        A(buf.getvalue()[:4000])
        A("```")
        A("")
        A("### Trades dataframe columns")
        A("")
        t = stats["_trades"]
        A("```")
        A(str(list(t.columns)))
        A("```")
        A("")
        A("first trades row(s):")
        A("```")
        A(t.head(2).to_string()[:2000])
        A("```")
        A("")
    except Exception as exc:  # pragma: no cover
        A(f"ERROR probing stats: {type(exc).__name__}: {exc}")
    A("")
    A("### Determinism note (verify) — two identical run() calls must produce identical trades")
    try:
        import numpy as np
        import pandas as pd
        n = 60
        idx = pd.date_range("2024-01-01", periods=n, freq="D", tz="UTC")
        rng = np.random.default_rng(7)
        close = 100 + np.cumsum(rng.normal(0, 1, n))
        df = pd.DataFrame({
            "Open": close * 0.999, "High": close * 1.01, "Low": close * 0.99,
            "Close": close, "Volume": rng.integers(1000, 5000, n),
        }, index=idx)

        class _Det(Strategy):
            def init(self):
                self.sma = self.I(lambda c: pd.Series(c).rolling(5).mean(), self.data.Close)

            def next(self):
                if not self.position and self.data.Close[-1] > self.sma[-1]:
                    self.buy(sl=self.data.Close[-1] * 0.95, tp=self.data.Close[-1] * 1.05)
                elif self.position and self.data.Close[-1] < self.sma[-1]:
                    self.position.close()

        b1 = Backtest(df, _Det, cash=10_000, commission=0.0001).run()
        b2 = Backtest(df, _Det, cash=10_000, commission=0.0001).run()
        A("two identical runs -> trades identical: " + str(b1["_trades"].equals(b2["_trades"])))
        A("equity final equal: " + str(float(b1["Equity Final [$]"]) == float(b2["Equity Final [$]"])))
        A("")
    except Exception as exc:  # pragma: no cover
        A(f"ERROR determinism probe: {type(exc).__name__}: {exc}")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"WROTE {OUT}")
    print("\n".join(lines[:80]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
